### ISSUE TITLE
关于ReactComponent.prototype.isReactClass

### ISSUE THREAD

**Issue by JxSx** [turbox3d/turbox#13]
在`Reactive.tsx`22行`Target.prototype.isReactClass`。

貌似应改为`Target.prototype.isReactComponent`

**Comment by geoffgu** [comment]
我先关了。
* 这段代码是为了判断是否是 class component 而不是 react component
* 虽然属于 react16 时代的产物，但也兼容 react17,18，新版本越来越弱化 class component 的使用，后续推荐使用 functional component 的包裹写法
